services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animal_shelter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: satek123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # command override for development (--reload)
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:satek123@mysql:3306/animal_shelter_db
    depends_on:
      - mysql
    networks:
      - app_network

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "8080:8080"  # development: serve directly on port 8080 with hot-reloading
    # - "8080:80"    # production:  serve via NGINX on port 8080 mapped to port 80 inside the container
    volumes:
      - ./web-app:/app
      - /app/node_modules
    environment:
      - VUE_APP_BACKEND_URL=http://backend:8000
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
