services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # command override for development (--reload)
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://my_user:my_password@mysql:3306/my_database
    depends_on:
      - mysql
    networks:
      - app_network

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    volumes:
      - ./web-app:/app
      - /app/node_modules  # avoid reinstalling dependencies
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
